### ISSUE TITLE
Patient View Page - Doctor.image_url

### ISSUE THREAD

**Issue by sbrks** [GA-Project3/Physical-Therapy-App#36]
This page is breaking at the line that calls image_url on @doctor. I believe this is because the @doctor here is referring to the patient's doctor attribute, which does not itself have an image_url property.

**Comment by mnorelli** [comment]
This actually works.  @doctor was passed in from the Patients controller on the show method

**Comment by mnorelli** [comment]
close if there isn't a remaining problem?

**Comment by mnorelli** [comment]
Sam pulled and got this problem fixed
